 drop table if exists CONTACTS_1
;

CREATE TABLE CONTACTS_1 (
    id INT NOT NULL AUTO_INCREMENT,
    firstname VARCHAR(30),
    lastname VARCHAR(30),
    telephone VARCHAR(15),
    email VARCHAR(30),
    created TIMESTAMP DEFAULT NOW(),
    PRIMARY KEY ( id )
)
;

 drop table if exists CONTACTS
;

CREATE TABLE CONTACTS (
    CONTACTID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(30),
    EMAIL VARCHAR(30),
    MESSAGE VARCHAR(15),    
    CREATEDBY INT DEFAULT 0,
    CREATEDON TIMESTAMP DEFAULT NOW(),
    LASTUPDATEDBY INT DEFAULT 0,
    LASTUPDATEDON TIMESTAMP DEFAULT NOW(),
    PRIMARY KEY ( CONTACTID )
)
;


